language: java
notifications:
  hipchat:
    rooms:
      secure: NIfboW17HFfSyDHzRy1qZMN6bGVPPq452aca+pSTxaNKm3y2cJvTbjcEMdb7xT+miNJXmWwgcNjK9xVdc1ZayO6h0HOX8UfiMle/MNV6fG4n/FabyAt9uol8ALpafiYLPRmpJjl5gah4vmhvwN4ca1HXRNGE1nqXivWeumY72DZvDuRwrfuF9e8ScZ5gx3Z+7C1MIqKbg4KnIWfe9N0lyIJX/3ZidwMDAfXsi/N7FHzGYirDZL6N9EtWw3KKtvHJkJ9Ih2qY2kctYbP4bt+IXIwV3LwZgCvBeO/1nP9BQYeNJJ45mnUHiu9mAXY0bBy0B7owC4qspjQGcXjH64KJBUgBn0yV8yOk2I40YOzMlSX/Pp3BI2OF1voJ+nZaXn1VeO8+SNadN7mHBsmJLZ3kvGJijRqzvN0RuLwhvpA40SSAEc+Z9Vqxepnq3NUWUe/gtZnxEXayXxEx7SMj14myp7gdn3NVidp+1Qu3rJiT8Og1AijAyogAlX8mTS41bwpxUv6pypWjYUubAdP8NY1LWsrsK/nyl+PrR1T5n39ayC23NK40x+HwlWsQbaoP+xIQ81TJ+Cr3KJDXM4QhUPudFlH87J8b3YrRmL4EfKjUHSsHPf1llTETljy040YW//ILbm0NodZ8FfF3BSfaIu/WxxoQ8a/FEGPF5kfxV0liFsM=
deploy:
  provider: releases
  api_key:
    secure: q6Vz0Y/fgelQaIJzeJ/YJdLewVuGPuOo9vKURw5Ht5msjl8pPrryXV6FTJIJM53cC/280cdU88zo1wEt3M5fZW67hL98F7M+kSR/g7KrTZ1LZPOnl5C8zoU/1BXMwr1+ahqa/s1RDI14hL1IZ+Ozv6T69tvjqfePGr56hT/oQ06rdU99Lpccv5seq7y/cBpHgK0766iVMy1mcLIuZrCp6BryfnZk7nSEAyvkFKfc99NfsH4yCzUtpmdIHWEU/9xv3XvUxwsFhwNH4CMg3xPVM0IySEgAcx5YkprNtKeOmZFpFwi1UBg5Dyj0txyMSxWAN12DGEh/AePwUcRivrTR7SmQzdfj6s95C2I4gJD5c/XHmuQvX3SNajPWe+LCrKmOJ0FKFWIr40q2rPXpXHD3CEW9r+7EGb++yPgMClNzPfALhStYN59Hcd0ohTohWivrJVbOGxDZ1ZaYSozpBlarcvLGTklZY4S52iELmOqbQPg9fXzg67KkuIZ85aXDzBEi9OW/WHVhOZPNrd9p/fiEmxQrZD9VGCesOrXRmQK51gLyy9nuprQtjOwNKyxNNN4FMg9vGCvWlR/0GiZYhFJwM944PoZSU76LxrSgp7AxGI3VhjG4hhehpyi2wUHwmiMzoW0V2GkHv0Owumr1aBErWioC9VTsQADZshmMTqKoCD8=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-was-set-dynamic-cluster-op-mode-plugin
