language: java
notifications:
  hipchat:
    rooms:
      secure: NIfboW17HFfSyDHzRy1qZMN6bGVPPq452aca+pSTxaNKm3y2cJvTbjcEMdb7xT+miNJXmWwgcNjK9xVdc1ZayO6h0HOX8UfiMle/MNV6fG4n/FabyAt9uol8ALpafiYLPRmpJjl5gah4vmhvwN4ca1HXRNGE1nqXivWeumY72DZvDuRwrfuF9e8ScZ5gx3Z+7C1MIqKbg4KnIWfe9N0lyIJX/3ZidwMDAfXsi/N7FHzGYirDZL6N9EtWw3KKtvHJkJ9Ih2qY2kctYbP4bt+IXIwV3LwZgCvBeO/1nP9BQYeNJJ45mnUHiu9mAXY0bBy0B7owC4qspjQGcXjH64KJBUgBn0yV8yOk2I40YOzMlSX/Pp3BI2OF1voJ+nZaXn1VeO8+SNadN7mHBsmJLZ3kvGJijRqzvN0RuLwhvpA40SSAEc+Z9Vqxepnq3NUWUe/gtZnxEXayXxEx7SMj14myp7gdn3NVidp+1Qu3rJiT8Og1AijAyogAlX8mTS41bwpxUv6pypWjYUubAdP8NY1LWsrsK/nyl+PrR1T5n39ayC23NK40x+HwlWsQbaoP+xIQ81TJ+Cr3KJDXM4QhUPudFlH87J8b3YrRmL4EfKjUHSsHPf1llTETljy040YW//ILbm0NodZ8FfF3BSfaIu/WxxoQ8a/FEGPF5kfxV0liFsM=
deploy:
  provider: releases
  api_key:
    secure: dlOSvfnoTZkvGGJGvGzBiIE+9HsvvcgL1ObseUBRRMQIs4Pzesnq0Gma4aGJ46Fk7xn9RLLliHrzwK6IdEDI9Inzj6PP5NPbO2LgXmqU91zMFDscNQRu2DqrQIMbuCk0SG8O5OH5GdTvUCSkn+q/XtN+n8exSTBW6HK7sEGaGGgVSxXf/VkQe1khkq47OJVhhAxaU/yqLvyk+9FoYlm/3j0gpnyAxFlCnXOpwluSLrcYBDxTDqINEH3cOKeAtmH9GgZRD17CIs44JVf6YVZcDfk5C4LQ5Oh3ftv1PWms3dBM9mcxnSDa0kLGoFN1Mi36Fhk6gxu7D/jWYs7zz1FaCrzZp2N5B5DpJBadOI81/Sv+se1yh9h5eVfDlVfKzqrWqmOW5EaGd/i+myM3uNsOD/bCFGbAj0Ud+1dj1hI2FSJBEZpnLyuHAydJn8YKnFYHQON2DKBctex2z/k49FqbgxqLcudU11Mu6E2hELrMKPBLr6/0WxITGzLbUFEtI6PbM9XkxBB/sbRiPWj5bpnzsRXkoPdNMwXiyOMb7bs7tru+t/4isLXN5LPHhUipCD3KvwQeXDLAcvkFeVlJnV7mPtmL8cqnhyDYi3w4roJxHOY/IWG0Ehk2JFPUDeuDBDin69GSK5onaeZoh4l6DyqzqOedc/1EFdfpUwAXTnMDbfA=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-was-set-dynamic-cluster-op-mode-plugin
