language: java
notifications:
  slack:
    secure: GAIiHaTN1qvAOgqm9rrJPrG3DwjHmxBH9oXe5RGbv7jwjQqPH/BzCku5TPN6CfDYGAo/QzMvgcyuxT9oHUJskL2fqNuF0iDmO7K5/uoMjIYjcTYL5haebI7DIb4ibMBTgLHzoQGpReRZbOsbh8sqCXXSlhIKmprq3NO9uQrkYWHeJHTPxt+pYDz8wZ+udjcAAq5hdETpja02+7mKlSK8yeltdnxuwi6MZr64gGMz8mB30rOx1KAN60cmNpGY/ssEs5LWn0xrbFbULVSbITxYtxwWfl51vkmwCoVLwNL9JAycHEcygFg8WbaNXthxfVseBKNIyrAnzcQyNT3UPRyp7KQH0fJuQ0qJSXVrhAM49OCfJzdf2IbdziQK233Tt/t2iPQW///+FyyIXDi6TQj/s0oulLAIUd5eQbVs7LtitXOfIsXM/0xP54E8h58yYGhamdGlJ5Kj9Rit4w/QghowLhwQrwkmASQVFz2zQQsTK4OSQJReguwehhhV19rTKI9SaNZHdFvEYP9M1USBS0+VAj2chxsp5IbV3oUrKApr8WyZSWPzu/77uxSm9RufZ9z4EdQvRKt5c1p9mT1SowQhfHdaeTeR7D2nf3r9ZV4hAPX4l1PCyHPs0V1rRPrqXtZGxg6deRu4IsmYbxXfc9FfYWtUzzeiwBVYghnLqyQnco4=
deploy:
  provider: releases
  api_key:
    secure: dlOSvfnoTZkvGGJGvGzBiIE+9HsvvcgL1ObseUBRRMQIs4Pzesnq0Gma4aGJ46Fk7xn9RLLliHrzwK6IdEDI9Inzj6PP5NPbO2LgXmqU91zMFDscNQRu2DqrQIMbuCk0SG8O5OH5GdTvUCSkn+q/XtN+n8exSTBW6HK7sEGaGGgVSxXf/VkQe1khkq47OJVhhAxaU/yqLvyk+9FoYlm/3j0gpnyAxFlCnXOpwluSLrcYBDxTDqINEH3cOKeAtmH9GgZRD17CIs44JVf6YVZcDfk5C4LQ5Oh3ftv1PWms3dBM9mcxnSDa0kLGoFN1Mi36Fhk6gxu7D/jWYs7zz1FaCrzZp2N5B5DpJBadOI81/Sv+se1yh9h5eVfDlVfKzqrWqmOW5EaGd/i+myM3uNsOD/bCFGbAj0Ud+1dj1hI2FSJBEZpnLyuHAydJn8YKnFYHQON2DKBctex2z/k49FqbgxqLcudU11Mu6E2hELrMKPBLr6/0WxITGzLbUFEtI6PbM9XkxBB/sbRiPWj5bpnzsRXkoPdNMwXiyOMb7bs7tru+t/4isLXN5LPHhUipCD3KvwQeXDLAcvkFeVlJnV7mPtmL8cqnhyDYi3w4roJxHOY/IWG0Ehk2JFPUDeuDBDin69GSK5onaeZoh4l6DyqzqOedc/1EFdfpUwAXTnMDbfA=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-was-set-dynamic-cluster-op-mode-plugin
